# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [25]:
import numpy as np

a=np.arange(1,11)
print(a)


[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

In [6]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

In [8]:
c=np.linspace(0,5,10)
print(c)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

In [26]:
d=np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [13]:
e=np.random.random((4,4))
print(e)

[[0.70785627 0.09958585 0.95047531 0.87138243]
 [0.54996889 0.92308175 0.22288737 0.63677999]
 [0.17556825 0.67160257 0.48027526 0.28119286]
 [0.56181194 0.28988398 0.09020408 0.78989392]]


In [27]:
np.random.seed(100)
A=np.random.rand(3,4)
A

array([[0.54340494, 0.27836939, 0.42451759, 0.84477613],
       [0.00471886, 0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195, 0.20920212]])

In [28]:
np.random.seed(0)
A=np.random.rand(3,4)
A

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

In [16]:
print(d.shape)

(5, 5)


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [18]:
f=np.arange(16)
f.shape=(4,4)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

In [19]:
print(f.dtype)

int64


### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

In [22]:
g=np.arange(1,101)
eve=[]
for i in g:
    if i % 2 == 0:
        eve.append(i)
print(eve)    

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [30]:
A=[x for x in np.arange(1,101) if x % 2 ==0]
A

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [34]:
B=np.arange(2,101,2)
B

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

In [30]:
C=np.random.randint(10,50,(6,6))
C

array([[20, 23, 22, 22, 35, 39],
       [13, 43, 20, 22, 48, 10],
       [39, 12, 38, 40, 19, 17],
       [36, 25, 24, 20, 26, 40],
       [17, 22, 22, 20, 15, 14],
       [42, 38, 34, 18, 30, 40]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

In [36]:
c=C[2:4,2:4]
c


array([[34, 39],
       [42, 11]])

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

In [47]:
print(np.sum(c))

126


### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [45]:
print(np.mean(C))
print(np.std(C))
print(np.median(C))

29.75
12.033229454768621
29.0


# Exercise 14:
Find the maximum and minimum values in a NumPy array.



In [44]:
print(np.max(C))
print(np.min(C))

49
10


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [83]:
d=np.arange(20)
print(d)
np.argmax(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


19

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

In [66]:
G=np.random.rand(3,3)
print(G)
print(np.flip(G))

[[0.29071191 0.48877028 0.02993737]
 [0.8784246  0.11064256 0.70479216]
 [0.02719993 0.189782   0.77120466]]
[[0.77120466 0.189782   0.02719993]
 [0.70479216 0.11064256 0.8784246 ]
 [0.02993737 0.48877028 0.29071191]]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

In [70]:
G=np.random.rand(3,3)
B=np.random.rand(3,3)
print(G*B)
print(np.multiply(G,B))

[[0.03430897 0.17060636 0.03700547]
 [0.00927631 0.07882719 0.00348444]
 [0.01159262 0.34417238 0.06643891]]
[[0.03430897 0.17060636 0.03700547]
 [0.00927631 0.07882719 0.00348444]
 [0.01159262 0.34417238 0.06643891]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

In [85]:
F=np.arange(10,20)
print(F)
print(np.diag(F))

[10 11 12 13 14 15 16 17 18 19]
[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

In [8]:
G=np.random.rand(3,3)
B=np.random.rand(3,3)
print(np.dot(G,B))

[[0.23232538 0.87342354 0.95441784]
 [0.45094562 0.87433542 1.14630239]
 [0.60914066 0.25695275 0.60675336]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

In [4]:
G.shape=(9,)
print(G)

[0.65977146 0.97189492 0.4186511  0.78168609 0.72733624 0.47134868
 0.04029131 0.56174031 0.65269402]


### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

In [10]:
x=np.vstack((G,B))
print(x)

[[0.94260661 0.55418537 0.03214944]
 [0.84428666 0.92175202 0.37126182]
 [0.10371389 0.4189283  0.99649383]
 [0.14714936 0.85141439 0.76957576]
 [0.13772062 0.12102336 0.39212535]
 [0.53807073 0.11836414 0.3639413 ]]


### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

In [11]:
y=np.hstack((G,B))
print(y)

[[0.94260661 0.55418537 0.03214944 0.14714936 0.85141439 0.76957576]
 [0.84428666 0.92175202 0.37126182 0.13772062 0.12102336 0.39212535]
 [0.10371389 0.4189283  0.99649383 0.53807073 0.11836414 0.3639413 ]]


### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

In [12]:
print(np.split(G,3))

[array([[0.94260661, 0.55418537, 0.03214944]]), array([[0.84428666, 0.92175202, 0.37126182]]), array([[0.10371389, 0.4189283 , 0.99649383]])]


### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

In [29]:
print(np.round(np.random.randint(0,20,(4,4))))

[[ 9  1  2  5]
 [ 0 11 13  9]
 [ 4  8 11  7]
 [ 4 16 16  2]]


### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

In [32]:
print(np.unique(C))
print(C)

[10 12 13 14 15 17 18 19 20 22 23 24 25 26 30 34 35 36 38 39 40 42 43 48]
[[20 23 22 22 35 39]
 [13 43 20 22 48 10]
 [39 12 38 40 19 17]
 [36 25 24 20 26 40]
 [17 22 22 20 15 14]
 [42 38 34 18 30 40]]


### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

In [33]:
C[C<27]=30
print(C)

[[30 30 30 30 35 39]
 [30 43 30 30 48 30]
 [39 30 38 40 30 30]
 [36 30 30 30 30 40]
 [30 30 30 30 30 30]
 [42 38 34 30 30 40]]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

In [34]:
print(np.cumsum(C))

[  30   60   90  120  155  194  224  267  297  327  375  405  444  474
  512  552  582  612  648  678  708  738  768  808  838  868  898  928
  958  988 1030 1068 1102 1132 1162 1202]


### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

In [43]:
z=np.random.rand(4)
b=np.diag(z)
print(b)
print(z)
print(np.count_nonzero(b))

[[0.87664807 0.         0.         0.        ]
 [0.         0.59275906 0.         0.        ]
 [0.         0.         0.15143489 0.        ]
 [0.         0.         0.         0.17030576]]
[0.87664807 0.59275906 0.15143489 0.17030576]
4


### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

In [46]:
z=np.random.randint(10,44,(5,5))
print(z)
print(np.sort(z))

[[38 25 33 41 15]
 [41 23 14 31 22]
 [35 15 19 43 32]
 [41 34 27 36 13]
 [41 40 14 24 31]]
[[15 25 33 38 41]
 [14 22 23 31 41]
 [15 19 32 35 43]
 [13 27 34 36 41]
 [14 24 31 40 41]]


### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

In [50]:
d=np.random.randint(3,10,(3,3))
print(d)
print(np.sum(d, axis=1))
print(np.sum(d, axis=0))

[[7 8 8]
 [4 5 8]
 [6 8 4]]
[23 17 18]
[17 21 20]


### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---